version: "3.6"
services:
  ui:
    build:
      context: "./ui"
      dockerfile: "Dockerfile"
      target: "dev"
    restart: on-failure
    volumes:
      - "./ui/src:/app/src"
      - "./ui/node_modules:/app/node_modules"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      REACT_APP_API_URL: "http://localhost:8081"
      REACT_APP_SIGNALLING_URL: "ws://localhost:8081/signalling/ws"
      REACT_APP_STRIPE_PUBLISHABLE_KEY: pk_test_51ILSkYKHbgvdgLLAjc8dIh9ectl7gFQA0YbaohGIIVTAt21u2occaDi8MaKo0m30spgfiIrLmVgPNXoBWccmU5dZ00AJURLb0q
    ports:
      - "8080:3000"
    depends_on:
      - api
  api:
    build:
      context: "./api"
      dockerfile: "Dockerfile"
      target: "dev"
    volumes:
      - "./api/:/api"
    ports:
      - "8081:8080"
    depends_on:
      - db
  db:
    image: postgres:13.1-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: grindsapp
      POSTGRES_USER: grindsapp
      POSTGRES_PASSWORD: grindsapp
    volumes:
      - "./pg:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "grindsapp@grindsapp.localhost"
      PGADMIN_DEFAULT_PASSWORD: "grindsapp"
    ports:
      - "8082:80"
    volumes:
      - "./pgadmin4/servers.json:/pgadmin4/servers.json"
    restart: unless-stopped
    depends_on:
      - db
    logging:
      driver: none
