bind:
  address: "0.0.0.0"
  port: "8080"
database:
  host: db
  user: grindsapp
  password: grindsapp
  database: grindsapp
  port: 5432
ui:
  base_url: "https://localhost:8080"
billing:
  allow_instant_payouts: true
  profit_margin: 16
  stripe:
    publishable_key: pk_test_51ILSkYKHbgvdgLLAjc8dIh9ectl7gFQA0YbaohGIIVTAt21u2occaDi8MaKo0m30spgfiIrLmVgPNXoBWccmU5dZ00AJURLb0q
    secret_key: sk_test_51ILSkYKHbgvdgLLA7GvSL7nEqa3byPMguk4Q4o0CXbV7hCzv4lSRetaEdz37yqHmX0Ep2lLDuofoDztto9rHcfB600mxs4cP9d
    account_link:
      return_url: "https://localhost:8080/account/billing"
      refresh_url: "https://localhost:8080/account/billing/onboarding"
signalling_secret: "SUPERSECRETKEY"
auth:
  jwt:
    # jwt lifetime
    ttl: 31536000
    private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEA5Co+UQw9fJj4k+1cZCFu1bLcspl87qMSieM7qg+BPckfwrP0
      WrSgu8i4pUzmiP+sZrXQ2/WC6UF6bUc3CHfzyEJj20iUj8heSvvjqoMMMASrJSCX
      abOPE2Bp6XGIwx+S086EiK8HrpnUkrQSHn4MwhiGjeXzoi/LMLBO/Jl6OB7F51TG
      IG62NLW9dPfEwgAvm09vHz/cy2p/denmLO7ZkyQcmkPAUpsuBvaoQmkNl2IW2l/2
      YEMxN++XWxuWsrFXgKOYkG8Ira5c4y6930Rq+ehtU3p1rXAueAJ6fmTW0TZ7/KCj
      YvUOLSslx0T3cYlzaj7v5G9nbqoy/oXl3QqbVQIDAQABAoIBABkbvPfWTP3lJ5W/
      zScHtta1dCwDUAhC0ctywiIYyrQt6dzXSNCih/2iPQ+TwtrYp/Q1leJexiU9G2fj
      Kl84NA+ZnruG5TJdbmL6DTe6bCDsopjXWVI8fEY5me4inFY8pz+/vj38ZPAF5aqv
      Pj80x9qkMEp1P7ZdZBLblBWgHh8GrqmxJsEv4ipvH22wLv4D+y784pxRzqsv18h1
      6opEw6XYPdv/zZ4aSlXRERH+U0DGHdwC/FCX5m6nlK+RCyMY9jY2VgsDSTbHpEq8
      ABoCpz9J/1yw9OYVOvc2MPiW0ONxAadKMAhKBOU9+sRxWYOy/OublBBxjMmBlpXU
      3xC3U5ECgYEA/MFDvTX7JiPJLHVPyT5kczwKR3+hgF6RxaDcozSE27k7YXCEkNKD
      QMAhMuY+jIkiej2ej84gyDkIRkpGlZKWRXvlrcwhBVQGWgJbV6ztZ0C35aQHP30i
      06l0SDaarkfLJ40diTyV8ZS+ZL1vxhRxR3Oi2p82yUxBWNyNGYBnZAsCgYEA5xgo
      lq0peCFZQuC3k6UC6rIv8TNEzdYcWPy/WNRf17Ta07fQu/+Zi02HQ45zTGk2bmQ3
      GFoK4AfrUM/iHPMXwhwmaM1YOl4HCFTRT4yv2lYucrfQ3Z+vbfWPd8Ex5bkzfZnU
      V4quuTtSfIPvrLY+WAdYps4JuAJg5cvOUBFxOh8CgYAc3AhbA13g1fczb1Wj2c7o
      ZXObBFSxbprgYOSwcd+1ounHz2wjiRXZf9aKlEWSEFpycLS5IMUXd4OdWv/CNlGY
      L3RjKsqebCCpiFlbonAc+QPGYbs+IZCncFLJqApzWdk1c+RqdhN82QoAQK0RheYF
      TYvLwKAlzeIsPkqSHdowTwKBgQCa32zsNhaRpL/eex1sfGzs/wf0POjCjdinppNS
      I9orhNAWjZz9MTokyot5MfGBZw2Mg+sMjeO16njAyuD9h8kHVLhFCkEztKo/4h/4
      kQ+VYqZ0SU5YCNmX9rb0iew3yZuBdGODW7Tm/KO2QPGSLPyxIBNAjtqikC2CM8kL
      jfT0/wKBgQDGI+txHkl+NSZc889sGL7h+mNg1i7BXXLfmG/2HahYF6QiO1cnIC0a
      gohQO9sbxUCk3Vj/f+zqsa9pbC2mZkgvaOr9unhuxNKnkUIOHyCqQi1u0YA9t8e5
      /+RtZ8ZrqQNLY8Yta/mXSuycnLCkF0+/7Rx4DIRK/0Oo4gbRwduTAg==
      -----END RSA PRIVATE KEY-----
    public_key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5Co+UQw9fJj4k+1cZCFu
      1bLcspl87qMSieM7qg+BPckfwrP0WrSgu8i4pUzmiP+sZrXQ2/WC6UF6bUc3CHfz
      yEJj20iUj8heSvvjqoMMMASrJSCXabOPE2Bp6XGIwx+S086EiK8HrpnUkrQSHn4M
      whiGjeXzoi/LMLBO/Jl6OB7F51TGIG62NLW9dPfEwgAvm09vHz/cy2p/denmLO7Z
      kyQcmkPAUpsuBvaoQmkNl2IW2l/2YEMxN++XWxuWsrFXgKOYkG8Ira5c4y6930Rq
      +ehtU3p1rXAueAJ6fmTW0TZ7/KCjYvUOLSslx0T3cYlzaj7v5G9nbqoy/oXl3Qqb
      VQIDAQAB
      -----END PUBLIC KEY-----
